### ISSUE TITLE
roadmap / feature lists / todo list...

### ISSUE THREAD

**Issue by andrzejsliwa** [extend/farwest#3]
Hi, could you share with us more info about farwest? Maybe we could take some efforts to speed up development process?

lots of pains in Erlang community we have because people working on reinventing wheel in non open source projects (**S**elfish **E**rlanger **S**yndrome (**SES** :-D) - there is lots of examples of this syndrome, I asked many intermediate erlang developers for basic toolsets/scripts or stuff/tricks which are very often 'secret weapon' of authors and are held in dungeons of private scm's).
I think we really need to join forces to prepare quality projects with strong momentum to growing like Rails/Ruby or Django/Python community does.

Best Regards,
Andrzej

**Comment by essen** [comment]
Right. Sorry for all this going so slow.

There's two things being developed side by side right now.

Presence and sessions on one side, which is almost done, works in production at a client, distributed, per-session message queue, yada yada, but still needs cleanup before pushing. Should be done sometimes in September.

The UI for editing templates and data on another side, which works quite well, but this one is still a bit experimental at this point and won't be pushed yet.

Other parts are mostly just experiments that I don't really want to continue until I've made the changes to the Cowboy REST code I want (PATCH, reworked POST, etc.).

I'm not doing something like Rails or Django though, it's more a lot of loose components.

**Comment by andrzejsliwa** [comment]
BIG Thanks for fast response and feedback!

You could commit all **in progress** or **experimental** code, nobody expecting that this will be stable or ready as long there is no official release or version defined. But then we will have to chance to see what you have it already, even for inspiration or understanding your original architecture concept etc. Nobody expect that full working code just appear in one single commit :D

You could make even **experimental** branches ... to give sign: **no warranty that will stay in future**

Github is amazing thing... when you let code live its own life :D

BTW: Rails and Django were born when all loose components fits together :D

**Comment by essen** [comment]
But Rails and Django are big monolithic applications, while Farwest is intended to be a thin HTTP layer to your OTP applications (with some optional scaffolding components to allow frontend people to do many things by themselves before the OTP applications are ready).
