### ISSUE TITLE
Build from make fails, certificate issue?

### ISSUE THREAD

**Issue by varnerac** [extend/farwest#6]
When I try to build farwest, it complains about raw.gitub.com's certificate:

<pre>

server:~ varnerac$ git clone https://github.com/extend/farwest.git
Cloning into 'farwest'...
remote: Counting objects: 145, done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 145 (delta 40), reused 127 (delta 25)
Receiving objects: 100% (145/145), 70.91 KiB | 0 bytes/s, done.
Resolving deltas: 100% (40/40), done.
Checking connectivity... done
server:~ varnerac$ cd farwest/
server:farwest varnerac$ make
rm -rf rel/farwest
--2013-11-29 00:29:50--  https://raw.github.com/extend/erlang.mk/master/packages.v1.txt
Resolving raw.github.com (raw.github.com)... 199.27.72.133
Connecting to raw.github.com (raw.github.com)|199.27.72.133|:443... connected.
ERROR: The certificate of ‘raw.github.com’ is not trusted.
ERROR: The certificate of ‘raw.github.com’ hasn't got a known issuer.
make: *** [/Users/varnerac/farwest/deps/farwest_core] Error 5
server:farwest varnerac$ make
rm -rf rel/farwest
git clone -n -- `awk 'BEGIN { FS = "\t" }; $1 == "farwest_core" { print $2 }' /Users/varnerac/farwest/.erlang.mk.packages.v1` /Users/varnerac/farwest/deps/farwest_core
fatal: repository '/Users/varnerac/farwest/deps/farwest_core' does not exist
make: *** [/Users/varnerac/farwest/deps/farwest_core] Error 128
server:farwest varnerac$ wget -V
GNU Wget 1.14 built on darwin13.0.0.

+digest +https +ipv6 +iri +large-file +nls -ntlm +opie +ssl/gnutls 

Wgetrc: 
    /opt/local/etc/wgetrc (system)
Locale: /opt/local/share/locale 
Compile: /usr/bin/clang -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/opt/local/etc/wgetrc" 
    -DLOCALEDIR="/opt/local/share/locale" -I. -I../lib -I../lib 
    -I/opt/local/include -pipe -Os -arch x86_64 
Link: /usr/bin/clang -pipe -Os -arch x86_64 -L/opt/local/lib 
    -Wl,-headerpad_max_install_names -liconv -lintl -arch x86_64 -lintl 
    -Wl,-framework -Wl,CoreFoundation -lgnutls -lgcrypt -lgpg-error -lz 
    -lz -lidn -lpcre ftp-opie.o gnutls.o ../lib/libgnu.a 

Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
server:farwest varnerac$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
server:farwest varnerac$ 

</pre>

**Comment by kiela** [comment]
It's not issue with farwest itself, it's issue with your OS and certificates:

```
Connecting to raw.github.com (raw.github.com)|199.27.72.133|:443... connected.
ERROR: The certificate of ‘raw.github.com’ is not trusted.
ERROR: The certificate of ‘raw.github.com’ hasn't got a known issuer.
```

**Comment by essen** [comment]
It's something that will be fixed very soon in erlang.mk, but you can also fix it system-wide (no idea how).

**Comment by varnerac** [comment]
The solution is to create a <code>.wgetrc</code> file in your home directory with the line:

<pre>check_certificate = off</pre>

Otherwise, the build will fail on OS X Mavericks with wget install from MacPorts.

**Comment by essen** [comment]
erlang.mk doesn't check for certificates anymore, you don't need the file now. Thanks for the heads up!
