### ISSUE TITLE
farwest fails to start

### ISSUE THREAD

**Issue by varnerac** [extend/farwest#7]
<pre>
 server:farwest varnerac$ ./rel/farwest/bin/farwest console
Exec: /Users/varnerac/farwest/rel/farwest/erts-5.10.3/bin/erlexec -boot /Users/varnerac/farwest/rel/farwest/releases/dev/farwest -mode embedded -config /Users/varnerac/farwest/rel/farwest/releases/dev/sys.config -args_file /Users/varnerac/farwest/rel/farwest/releases/dev/vm.args -- console
Root: /Users/varnerac/farwest/rel/farwest
heart_beat_kill_pid = 70714
Erlang R16B02 (erts-5.10.3) [source] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:true]

=INFO REPORT==== 1-Dec-2013::00:38:49 ===
    application: cowboy
    exited: {bad_return,
                {{cowboy_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{cowboy_app,start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,269}]}]}}}}
    type: permanent
{"Kernel pid terminated",application_controller,"{application_start_failure,cowboy,{bad_return,{{cowboy_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy_app,start,[normal,[]],[]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,269}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_starheart: Sun Dec  1 00:38:50 2013: t_fErlang is crashing .. (waiting for crash dump file)ai
lureheart: Sun Dec  1 00:38:50 2013: ,Would reboot. Terminating.c
owboy,{bad_return,{{cowboy_app,start,[normal,[]]},{'EXIT',{undef,[{cowboy_app,start,[normal,[]],[]},{application_master,st
</pre>

**Comment by essen** [comment]
The relx start script has an issue on OSX when the volume name has a space in it, and another I can't recall.

**Comment by varnerac** [comment]
Here is the same issue: http://stackoverflow.com/questions/20229970/exception-when-running-erlang-cowboy-web-server-in-mac-os-x

**Comment by varnerac** [comment]
In the generated farwest boot script at  <code>farwest/rel/farwest/releases/dev/farwest.script</code> the following section looks suspect:

<pre>
... START SNIP ...
     {path,["$ROOT/lib/compiler-4.9.3/ebin"]},
     {primLoad,
         [beam_a,beam_asm,beam_block,beam_bool,beam_bsm,beam_clean,beam_dead,
          beam_dict,beam_disasm,beam_except,beam_flatten,beam_jump,
          beam_listing,beam_opcodes,beam_peep,beam_receive,beam_split,
          beam_trim,beam_type,beam_utils,beam_validator,beam_z,cerl,
          cerl_clauses,cerl_inline,cerl_trees,compile,core_lib,core_lint,
          core_parse,core_pp,core_scan,erl_bifs,rec_env,sys_core_dsetel,
          sys_core_fold,sys_core_inline,sys_pre_attributes,sys_pre_expand,
          v3_codegen,v3_core,v3_kernel,v3_kernel_pp,v3_life]},
     {path,["$ROOT/lib/asn1-2.0.3/ebin"]},
     {primLoad,[asn1rt,asn1rt_nif]},
     {path,["$ROOT/lib/crypto-3.1/ebin"]},
     {primLoad,[crypto,crypto_app,crypto_server,crypto_sup]},
     {path,["$ROOT/lib/cowboy-0.9.0/ebin"]},
     {primLoad,[]},
     {path,["$ROOT/lib/erlydtl-0.7.0/ebin"]},
     {primLoad,
         [blocktrans_extractor,blocktrans_parser,blocktrans_scanner,erlydtl,
          erlydtl_compiler,erlydtl_contrib_humanize,erlydtl_dateformat,
          erlydtl_deps,erlydtl_filters,erlydtl_i18n,erlydtl_parser,
          erlydtl_runtime,erlydtl_scanner,erlydtl_slice,erlydtl_unparser,
          i18n_manager,po_generator,po_scanner,sources_parser]},
     {path,["$ROOT/lib/riak_pb-1.4.1.1/ebin"]},
     {primLoad,
         [riak_kv_pb,riak_pb,riak_pb_codec,riak_pb_kv_codec,
          riak_pb_search_codec,riak_search_pb]},
... END SNIP ...
</pre>

While it defines a path for <code>$ROOT/lib/cowboy-0.9.0/ebin</code>, it looks like it doesn't list any modules to load in the subsequent <code>primLoad</code> block. Would this explain why <code>cowboy_app</code> comes back <code>undef</code>?

**Comment by varnerac** [comment]
The missing <code>primLoad</code> piece was caused by the BSD sed implementation in OS X 10.9. I followed the recommendation here: https://github.com/extend/cowboy/issues/622#issuecomment-29176482 and replaced all calls to <code>sed</code> with <code>gsed</code>. You have to make sure you handle it in all of the <code>deps</code> as well. <code>make</code> will not pick up an <code>alias</code> command because it's not an interactive shell.

After fixing the BSD sed issue, I get the following error. I do not believe it's related. Let me know if you'd like me to create another issue.

<pre>
server:farwest varnerac$ ./rel/farwest/bin/farwest console
Exec: /Users/varnerac/farwest/rel/farwest/erts-5.10.3/bin/erlexec -boot /Users/varnerac/farwest/rel/farwest/releases/dev/farwest -mode embedded -config /Users/varnerac/farwest/rel/farwest/releases/dev/sys.config -args_file /Users/varnerac/farwest/rel/farwest/releases/dev/vm.args -- console
Root: /Users/varnerac/farwest/rel/farwest
heart_beat_kill_pid = 75867
Erlang R16B02 (erts-5.10.3) [source] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:true]
13:14:48.005 [info] Application lager started on node 'farwest@127.0.0.1'
13:14:48.005 [info] Application riakc started on node 'farwest@127.0.0.1'
13:14:48.007 [info] Farwest listening on port 8080
{"Kernel pid terminated",application_controller,"{application_start_failure,farwest_core,{{shutdown,{failed_to_start_child,fw_templates_server,{tcp,econnrefused}}},{farwest_core_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,farwest_core,{{shutdown,{failed_to_start_child,fw_templates_server,{tcp,econnrefused}}},{farwest_core_app,start,[normal,[]]
heart: Sun Dec  1 13:14:49 2013: Erlang is crashing .. (waiting for crash dump file)
heart: Sun Dec  1 13:14:49 2013: Would reboot. Terminating.
</pre>

**Comment by essen** [comment]
You probably need to configure the ports for riak.

**Comment by varnerac** [comment]
I submitted a pull request  (https://github.com/extend/erlang.mk/pull/35) to erlang.mk to fix the sed issue.

**Comment by essen** [comment]
Has been merged. Closing, thanks!
