### ISSUE TITLE
Help with To build 'make' failed

### ISSUE THREAD

**Issue by jiangyo4** [extend/farwest#9]
Hi All, 
## I just try to build farwest using  make .(I installed Erlang R16B03-1 ,  version 0.6.0 of relx  and make 4.0  on centos 6.4) but I get the error message:

make[3]: Entering directory '/home/farwest/deps/erlydtl/deps/merl'
erl -noshell -pa ebin \
 -eval 'eunit:test("ebin",[])' \
 -s init stop
  All 117 tests passed.
make[3]: Leaving directory '/home/farwest/deps/erlydtl/deps/merl'
make[2]: Leaving directory '/home/farwest/deps/erlydtl'
 ERLC   fw_userfiles_handler.erl fw_dashboard_handler.erl fw_userdata_bucket_handler.erl fw_templates_handler.erl fw_routes_handler.erl fw_userdata_handler.erl
 DTL    farwest_base.dtl fw_userfiles_collection.dtl fw_templates.dtl fw_routes.dtl fw_dashboard.dtl fw_userdata_collection.dtl fw_userdata_editor.dtl
{"init terminating in do_boot",{undef,[{merl,term,[<<72 bytes>>],[]},{erlydtl_beam_compiler,string_ast,2,[{file,"src/erlydtl_beam_compiler.erl"},{line,932}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1339}]},{erlydtl_beam_compiler,body_ast,3,[{file,"src/erlydtl_beam_compiler.erl"},{line,578}]},{erlydtl_beam_compiler,compile_to_binary,3,[{file,"src/erlydtl_beam_compiler.erl"},{line,189}]},{erlydtl_compiler,compile,1,[{file,"src/erlydtl_compiler.erl"},{line,177}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,eval_lc1,6,[{file,"erl_eval.erl"},{line,595}]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: **\* [ebin/farwest_ui.app] Error 1
make[1]: Leaving directory '/home/farwest/deps/farwest_ui'
make: **\* [deps] Error 2

Could you help me with this issue?

thanks

**Comment by rambocoder** [comment]
erlydtl has a dependency on merl
Did merl https://github.com/erlydtl/merl build for you?

**Comment by jiangyo4** [comment]
Thanks rambocoder .I  repeaetd  make merl(/home/farwest-master/deps/erlydtl/deps/merl) and erlydtl.However,I get  the same error .

make[2]: Entering directory `/home/farwest-master/deps/erlydtl'
==> erlydtl (get-deps)
Pulling merl from {git,"git://github.com/erlydtl/merl.git",{branch,"erlydtl"}}
Initialized empty Git repository in /home/farwest-master/deps/erlydtl/deps/merl/.git/
==> merl (get-deps)
==> erlydtl (compile)
make[3]: Entering directory`/home/farwest-master/deps/erlydtl/deps/merl'
erlc -pz ./priv -pa ./ebin  -o ebin/ src/merl.erl
erlc -DMERL_NO_TRANSFORM  -o priv/ src/merl_transform.erl
erlc -pz ./priv -pa ./ebin  -o ebin/ src/merl_transform.erl
erlc -pz ./priv -pa ./ebin  -o ebin/ src/merl_tests.erl
erl -noshell -pa ebin \
     -eval 'eunit:test("ebin",[])' \
     -s init stop
  All 117 tests passed.
make[3]: Leaving directory `/home/farwest-master/deps/erlydtl/deps/merl'
Compiled src/erlydtl_parser.yrl
Compiled src/erlydtl_library.erl
Compiled src/erlydtl_deps.erl
Compiled src/erlydtl.erl
Compiled src/filter_lib/erlydtl_dateformat.erl
Compiled src/filter_lib/erlydtl_slice.erl
Compiled src/i18n/blocktrans_scanner.erl
Compiled src/i18n/blocktrans_parser.erl
Compiled src/i18n/po_generator.erl
Compiled src/i18n/blocktrans_extractor.erl
Compiled src/erlydtl_compiler.erl
Compiled src/i18n/po_scanner.erl
Compiled src/i18n/i18n_manager.erl
Compiled src/erlydtl_i18n.erl
Compiled src/i18n/sources_parser.erl
Compiled src/erlydtl_scanner.erl
Compiled src/erlydtl_contrib_humanize.erl
Compiled src/erlydtl_runtime.erl
Compiled src/erlydtl_filters.erl
Compiled src/erlydtl_compiler_utils.erl
Compiled src/erlydtl_unparser.erl
Compiled src/erlydtl_beam_compiler.erl
Compiled src/erlydtl_parser.erl
make[2]: Leaving directory`/home/farwest-master/deps/erlydtl'
 ERLC   fw_dashboard_handler.erl fw_routes_handler.erl fw_templates_handler.erl fw_userdata_bucket_handler.erl fw_userdata_handler.erl fw_userfiles_handler.erl
 DTL    farwest_base.dtl fw_dashboard.dtl fw_routes.dtl fw_templates.dtl fw_userdata_collection.dtl fw_userdata_editor.dtl fw_userfiles_collection.dtl
{"init terminating in do_boot",{undef,[{erlydtl_compiler,compile,["templates/farwest_base.dtl",farwest_base_dtl,[{out_dir,"ebin/"}]],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},{erl_eval,eval_lc1,6,[{file,"erl_eval.erl"},{line,595}]},{erl_eval,eval_generate,7,[{file,"erl_eval.erl"},{line,624}]},{erl_eval,eval_lc,6,[{file,"erl_eval.erl"},{line,581}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,364}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,118}]},{init,start_it,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make[1]: **\* [ebin/farwest_ui.app] error 1
make[1]: Leaving directory `/home/hljaic/farwest-master/deps/farwest_ui'
make: **\* [deps] error 2

**Comment by funston** [comment]
any resolution for this, getting the same error

**Comment by essen** [comment]
Closing all tickets in this repo since there are no plans for this project under its current form.
